### ISSUE TITLE
User can see the home page

### ISSUE THREAD

**Issue by mja2128** [OpenClassrooms-Student-Center/Project-10-Bank-API#2]
A user should be able to:

- [ ] Navigate to the home page (`/`)
- [ ] See all placeholder data from mockup

**Comment by bencodezen** [comment]
Hi @mja2128! Did you create this issue accident?

**Comment by mja2128** [comment]
Yup, sorry about that. I forgot to clone the repo first before creating the
issues. My apologies! Please disregard that.

Best Regards,
Mike
