### ISSUE TITLE
yarn dev:server renvoi cette erreur , j'ai reinstallé plusieurs fois mongodb, j'ai bien verifié que mongo et ses services tournent sur ma machine, mais j'ai toujours cette erreur

### ISSUE THREAD

**Issue by AnisGhub** [OpenClassrooms-Student-Center/Project-10-Bank-API#26]
$ yarn dev:server
yarn run v1.22.19
warning ..\..\..\package.json: No license field
$ nodemon ./server/server.js
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./server/server.js`
Server listening on http://localhost:3001
Database Connectivity Error: MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
C:\Users\anis\Desktop\OpenClassRooms\Project-10-Bank-API\server\database\connection.js:10
    throw new Error(error);
          ^

Error: MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
    at module.exports (C:\Users\anis\Desktop\OpenClassRooms\Project-10-Bank-API\server\database\connection.js:10:11)

Node.js v18.16.1
[nodemon] app crashed - waiting for file changes before starting...

**Comment by cymard** [comment]
Salut @AnisGhub, j'ai eu la même erreur que j'ai résolu, en modifiant le server.js. Il faut que tu fasses le `dotEnv.config` avant de require le fichier de connexion `const dbConnection = require('./database/connection')`. 

Comme ça :
`const dotEnv = require('dotenv')`
`dotEnv.config();`
`const dbConnection = require('./database/connection')`
`dbConnection();`

**Comment by AnisGhub** [comment]
Merci @cymard mais finalement je l'ai résolu en changeant la variable de conf dans .env
de DATABASE_URL="mongodb://localhost/argentBankDB" à DATABASE_URL="mongodb://127.0.0.1:27017/argentBankDB"
normalment c'est la meme chose mais visiblement mon service mongo quand il tourne il préfère écouté 127.0.0.1:27017 :D
