### ISSUE TITLE
Database Connectivity Error on macOS

### ISSUE THREAD

**Issue by loicpoccard** [OpenClassrooms-Student-Center/Project-10-Bank-API#6]
# Unable to connect to the mongodb database.

After typing the following command `npm run dev:develop` :

<img width="715" alt="Capture d’écran 2021-04-26 à 03 03 08" src="https://user-images.githubusercontent.com/46573923/116572040-e7957c00-a90b-11eb-8333-c6e5d3078f58.png">

I tried to follow this topic [Server Discovery And Monitoring engine is deprecated](https://stackoverflow.com/questions/57895175/server-discovery-and-monitoring-engine-is-deprecated/57900760#57900760) but the problem persists...

**Comment by bencodezen** [comment]
Hey @Poccardl! Sorry for the delay in seeing this. Did everything work out?

**Comment by Noucho** [comment]
Hello, I have the same issue, can you help me please ?
I'm on Win x32

Thanks
